### ISSUE TITLE
[Question] Will Tango support adb over Wi-Fi? Is it even possible? 

### ISSUE THREAD

**Issue by kainbryanjones** [yume-chan/tango-feedback#11]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How would you like Tango to be improved?

I see in the demo it's stated "Tango can't connect to devices over WiFi". Will this feature be supported in future? Is it even possible?

![image](https://github.com/tango-adb/feedback/assets/89807193/3733dd61-1679-471d-92c4-cddc68d2a200)

### How do you think it should work?

.

**Comment by yume-chan** [comment]
Tango doesn't support wireless connection because Web browsers have no API to do that. It's not possible for Web apps.

We are developing a Desktop (download) version, which will support wireless connection.

**Comment by yume-chan** [comment]
You can subscribe #4 for the progress of the Desktop version.
