### ISSUE TITLE
[Bug] [Scrcpy] top bar doesn't hide in fullscreen with WCO

### ISSUE THREAD

**Issue by CorruptionVR** [yume-chan/tango-feedback#13]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the problem I had

### The environment Tango is running in

chromeOS , 119 stable

### The device you're connecting to

N/A

### What did you do and what happened?

I installed the web app as a PWA
enabled window-controls-overlay
started scrcpy
enter fullscreen
what I mean by top bar is this
![image](https://github.com/tango-adb/feedback/assets/78228404/d6a62780-5a79-4fe8-8e28-e50a7085c3c5)

**Comment by yume-chan** [comment]
Thanks for reporting! This is now fixed in the latest version.
