### ISSUE TITLE
[Suggestion] use window.resizeTo in pip mode

### ISSUE THREAD

**Issue by CorruptionVR** [yume-chan/tango-feedback#14]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How would you like Tango to be improved?

I would like for the pip window to resize automatically using the window.resizeTo API

### How do you think it should work?

that when the device rotates, the pip window resizes to fit the screen ratio

### (Optional) Other information

https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeTo

**Comment by yume-chan** [comment]
Thanks for your suggestion, I have implemented it so the PIP window will automatically resize when device screen orientation changes.

Note that this feature requires Chrome version 121 (https://chromestatus.com/feature/5398995019235328, https://crbug.com/1354325, the current stable version is 120).
