### ISSUE TITLE
[Bug?] (UI) : overview menu button cursor display

### ISSUE THREAD

**Issue by CorruptionVR** [yume-chan/tango-feedback#2]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the problem I had

### The environment Tango is running in

chromeOS , 116 stable

### The device you're connecting to

N/A

### What did you do and what happened?

on the buttons in the overview menu=> 
![image](https://github.com/yume-chan/tango-feedback/assets/78228404/2058af26-2c8a-4bbc-b301-32582498222d)
The outside part has the cursor changed to "pointer", but the "open" button has the cursor set to "default".
I don't know if this is intentional or not. sorry if this wastes your time.

**Comment by yume-chan** [comment]
Thanks for reporting! This has been fixed now.
