### ISSUE TITLE
[Bug] [Scrcpy] Scroll input not working

### ISSUE THREAD

**Issue by CorruptionVR** [yume-chan/tango-feedback#20]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the problem I had

### The environment Tango is running in

Mac, windows 10, chromeOS: Chrome 121, 121, 120

### The device you're connecting to

samsung galaxy A53 5G, 14

### What did you do and what happened?

I tried scrolling, but nothing happens.

**Comment by yume-chan** [comment]
Thanks for reporting! I have fixed it in the latest version.

**Comment by CorruptionVR** [comment]
Confirmed, thank you.
