### ISSUE TITLE
[Bug] Can Not install

### ISSUE THREAD

**Issue by 0mm8** [yume-chan/tango-feedback#23]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the problem I had

### The environment Tango is running in

Chrome 155

### The device you're connecting to

Google pixel 7a

### What did you do and what happened?

Install apk

### (Optional) Browser console output

```Text
supportsCmd: true
supportsAbb: true
supportsAbbExec: true
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

**Comment by yume-chan** [comment]
> INSTALL_FAILED_NO_MATCHING_ABIS

This means you have an `.apk` file not for your device. Try to contact the app developer for a matching version (should be noted `arm64-v8a` for your Pixel 7a)

https://stackoverflow.com/a/24572239
