### ISSUE TITLE
[Suggestion] Add Remote Debugging page

### ISSUE THREAD

**Issue by CorruptionVR** [yume-chan/tango-feedback#5]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How would you like Tango to be improved?

hey, you should add the remote debugging page to the new app

### How do you think it should work?

add a new page labeled "Chromium debugging".

**Comment by leonway** [comment]
Can this library connect multiple devices simultaneously in one tab?

**Comment by leonway** [comment]
Can I support executing any adb command online? For example, adb shell ls

**Comment by leonway** [comment]
The website is“ https://app.tangoapp.dev/ ”Can the application be open source? I want to learn how to use it

**Comment by yume-chan** [comment]
Forgot to mention, because this project is closed sourced, I can't use debugger frontend hosted by Google. I can compile it and include it in the project.

**Comment by yume-chan** [comment]
It has been added back: https://help.tangoapp.dev/blog/2025/07/12/new-sign-in/#chrome-remote-debugger
