### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by leonway** [yume-chan/tango-feedback#6]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How would you like Tango to be improved?

Can I support executing any adb command online? For example, adb shell ls

### How do you think it should work?

Can this library connect multiple devices simultaneously in one tab?

### (Optional) Other information

The website is“ https://app.tangoapp.dev/ ”Can the application be open source? I want to learn how to use it

**Comment by yume-chan** [comment]
Please file one issue for one question, and library questions should be posted to https://github.com/yume-chan/ya-webadb/discussions.

> Can I support executing any adb command online? For example, adb shell ls

Yes, see https://tango-adb.github.io/docs/tango/commands/subprocess#start-process-in-raw-mode

> Can this library connect multiple devices simultaneously in one tab?

Yes

> Can the application be open source?

It will be, but it's not ready in terms of code quality. The old demo is open sourced: https://github.com/tango-adb/old-demo

**Comment by leonway** [comment]
Can setprop support the command for Android?

**Comment by leonway** [comment]
大佬牛逼！ 爱了

**Comment by yume-chan** [comment]
`setprop` can be called using the same method as `ls`

**Comment by CorruptionVR** [comment]
hey, maybe you could add the terminal emulator to the web app as well

**Comment by yume-chan** [comment]
The new app is for average users, so I want to create a GUI for frequently used features.

For example, an app developer can tell their users to use the dump logcat feature to download system log (like [Taichi](https://taichi.cool/zh/doc/adb.html#%E7%94%9F%E6%88%90%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97) does, but the user doesn't need to read the log themselves.

**Comment by yume-chan** [comment]
@leonway Please open a new discussion at https://github.com/yume-chan/ya-webadb/discussions if you have any other questions.
