### ISSUE TITLE
[Suggestion] use https://tangoapp.dev as landing page

### ISSUE THREAD

**Issue by CorruptionVR** [yume-chan/tango-feedback#9]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How would you like Tango to be improved?

I think that it would be nice if https://tangoapp.dev was a landing page for Tango. It would have an available feature list, planned features, and newly added features.

### How do you think it should work?

make https://tangoapp.dev not redirect you to https://app.tangoapp.dev, and make it have a link to https://app.tangoapp.dev

**Comment by yume-chan** [comment]
We now have a beautiful landing page (shown when no device is paired).
